spring:
  application:
    name: admin-service

server:
  port: 8084
  servlet:
    context-path: /api/admin-service/v1

aws:
  dynamodb:
    table-name: ADMIN

  sns:
    order-topic-arn: arn:aws:sns:us-east-1:200849340204:order-events
  sqs:
    inventory-queue: inventory-queue
    inventory-dlq: inventory-dlq

    notification-queue: notification-queue
    notification-dlq: notification-dlq

    order-completion-queue: order-completion-queue
    order-completion-dlq: order-completion-dlq

    order-state-queue: order-state-queue
    order-state-dlq: order-state-dlq

    payment-queue: payment-queue
    payment-dlq: payment-dlq
